### ISSUE TITLE
You're great!

### ISSUE THREAD

**Issue by navidmirzaie** [nitrag/TiParseJS#5]
Wish i knew this module earlier thank you so much!

**Comment by gimdongwoo** [comment]
I've been updated for Parse JS SDK 1.8.2
https://github.com/gimdongwoo/TiParseJS/tree/master/dist

& PR
https://github.com/nitrag/TiParseJS/pull/6

**Comment by nitrag** [comment]
Thanks!
On May 26, 2016 7:50 AM, "Dongwoo Gim" notifications@github.com wrote:

I've been updated for Parse JS SDK 1.8.2
https://github.com/gimdongwoo/TiParseJS/tree/master/dist

**Comment by navidmirzaie** [comment]
The new sdk's doesnt support collections anymore im curious how you guys implement collections in your project.

**Comment by nitrag** [comment]
That's interesting. I'm not using collections. @gimdongwoo any thoughts?

**Comment by navidmirzaie** [comment]
@nitrag so you use the object.extend i guess? and retrieve information?
